apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    helm:
      values: |
        replicaCount: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true