apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-test
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: harbor-test
    helm:
      values: |
        replicaCount: 2
    repoURL: https://github.com/rashmin-maker/root-app/tree/main/harbor-test/chart
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
