apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-deploy
  labels:
    app: harbor-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: harbor-test
  template:
    metadata:
      labels:
        app: harbor-test
    spec:
      containers:
      - name: nginx-web
        image: nginx
        ports:
        - containerPort: 80
        