apiVersion: v1
kind: Service
metadata:
  name: harbor-service
  labels:
    app: harbor-test
spec:
  selector:
    app: harbor-test
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
    